FROM registry.access.redhat.com/ubi8/openjdk-17-runtime

ENV LANGUAGE='en_US:en'

COPY --chown=185 target/micronaut-app-*.jar /deployments/micronaut-app.jar

EXPOSE 8080
USER 185
# ENV JAVA_OPTS="-Dmicronaut.environments=prod"
ENV JAVA_APP_JAR="/deployments/micronaut-app.jar"