FROM registry.access.redhat.com/ubi9-minimal:9.2
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root target/micronaut-app /work/application

EXPOSE 8080
USER 1001

CMD ["./application"]